# il ktiba ili mawjouda mas2oul aal fos(login)
security:
    encoders:
    #methode de cruptage de mdp
        FOS\UserBundle\Model\UserInterface: bcrypt
#hadhra
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        ROLE_SIMPLE_USER: ROLE_USER
        ROLE_MUNICIPALITE: ROLE_MUNICIPALITE

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
         #redirection
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                success_handler: redirect.after.login
                #redirection pre-logout
            logout:
                path:    /logout
                target:  /
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/forum$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
#naamelhoum brohi
        - { path: ^/admin/, role: ROLE_SUPER_ADMIN }
        - { path: ^/user/, role: ROLE_USER }
        - { path: ^/municipalite/, role: ROLE_MUNICIPALITE }
