<?php

namespace questionnaireBundle\Repository;

/**
 * AbonnementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbonnementRepository extends \Doctrine\ORM\EntityRepository
{
    //fonction ena snatha tethat ken hne bech yaref idha aamel ou nn
    public function findAbonnement($id,$username){
        $query=$this->getEntityManager()
            ->createQuery("
            SELECT a FROM questionnaireBundle:Abonnement a 
            WHERE
            a.idUser=:idUser AND a.idMunicipalite=:municipalite")
            ->setParameter('idUser',$username)
            ->setParameter('municipalite',$id);
        return $query->getResult();
    }
}
