<?php

namespace questionnaireBundle\Repository;

/**
 * historiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class historiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
