<?php

namespace questionnaireBundle\Repository;

/**
 * ProblemeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProblemeRepository extends \Doctrine\ORM\EntityRepository
{
}
