<?php

namespace sondageBundle\Repository;

/**
 * voteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class voteRepository extends \Doctrine\ORM\EntityRepository
{
    public function findVote($id,$username){
        $query=$this->getEntityManager()
            ->createQuery("
            SELECT v FROM sondageBundle:vote v 
            WHERE
            v.idUser=:idUser AND v.suggestion=:suggestion")
            ->setParameter('idUser',$username)
            ->setParameter('suggestion',$id);
        return $query->getResult();
    }
}
